name = "verifair-public-website"
main = ".open-next/worker.js"
compatibility_date = "2026-07-28"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[routes]]
pattern = "verifair.com.au"
custom_domain = true
